symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600  # Durée de validité du token en secondes (1 heure)
    throttle_limit: 3600  # Temps minimum entre deux demandes de réinitialisation
    enable_garbage_collection: true  # Supprime automatiquement les demandes expirées