security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            custom_authenticators:
                - App\Security\UserAuthenticator
            entry_point: App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: app_home  # Redirect to homepage after logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to login
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to logout
        - { path: ^/livres, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Public catalog
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Homepage and other public routes
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10